CREATE TABLE BRANDS (
    BRAND_ID BIGINT NOT NULL PRIMARY KEY,
    NAME VARCHAR(255) NOT NULL
);

CREATE TABLE PRICES (
    PRICE_ID BIGINT NOT NULL PRIMARY KEY,
    BRAND_ID BIGINT NOT NULL,
    START_DATE TIMESTAMP NOT NULL,
    END_DATE TIMESTAMP NOT NULL,
    PRICE_LIST BIGINT NOT NULL,
    PRODUCT_ID BIGINT NOT NULL,
    PRIORITY INT NOT NULL,
    PRICE DOUBLE PRECISION NOT NULL,
    CURR VARCHAR(3) NOT NULL,
    CONSTRAINT FK_PRICES_BRANDS FOREIGN KEY (BRAND_ID) REFERENCES BRANDS (BRAND_ID)
);
